### ISSUE TITLE
Unable to delete resources after creating snapshot or image

### ISSUE THREAD

**Issue by royge** [alibaba/packer-provider#25]
After creating the image it show an error in deleting security group.

> alicloud-ecs: Error delete security group failed, may still be around: Aliyun API Error: RequestId: B9212A42-1E07-45A8-9AE0-D940217B0234 Status Code: 403 Code: DependencyViolation Message: There is still instance(s) in the specified security group.

The ECS instance created by packer is still in stopped state and I need to release it manually and I also need to delete the VPC, VSWitch manually.

**Comment by zhuzhih2017** [comment]
@royge  I have logic to check whether the depended instance is been deleted in a time duration, In normal case, it should be deleted. How offen is this happy?

**Comment by zhuzhih2017** [comment]
@royge I have add some logic to reduce the hand resource clean possibility, you can try.
Thanks.

**Comment by royge** [comment]
@zhuzhih2017 I wasn't able to check this issue again. I will try it again. Thank you.
