### ISSUE TITLE
Error deleting vpc

### ISSUE THREAD

**Issue by yujunz** [alibaba/packer-provider#33]
The images created successfully but error deleting VPC.

```
==> alicloud-ecs: Deleting image snapshots.
==> alicloud-ecs: Creating image: packer-juicefs-node-1522915639
    alicloud-ecs: Detach keypair packer_5ac5d937-5b1c-c17c-23f7-9b739f6f57f7 from instance: i-2ze7zj85weet69vckag2
==> alicloud-ecs: Cleaning up 'EIP'
==> alicloud-ecs: Cleaning up 'instance'
==> alicloud-ecs: Cleaning up 'security group'
==> alicloud-ecs: Cleaning up 'vSwitch'
==> alicloud-ecs: Cleaning up 'VPC'
==> alicloud-ecs: Error deleting vpc, it may still be around: Aliyun API Error: RequestId: 2267AF22-9D65-4730-AB6B-8C41E1420DAC Status Code: 400 Code: Forbbiden Message: Active custom route in vpc.
==> alicloud-ecs: Deleting temporary keypair...
Build 'alicloud-ecs' finished.
```

The vpc can be deleted from console successfully although it includes a route table.

**Comment by li-wu** [comment]
@yujunz, did you solve the problem? Thanks.

**Comment by yujunz** [comment]
No. I didn't go further in this issue.

**Comment by mosuke5** [comment]
I also confirmed this error happened.

**Comment by zhuzhih2017** [comment]
@yujunz @mosuke5 Packer will try to delete the resource it created, but the resource cleanup has dependence.  In generally the dependency result can be cleanup in one minute. I can increase the waiting time to reduce the error like this, but if you can provide more information is better that I can check what's the real  reason lead the dependency can't be release in time?

**Comment by willmao** [comment]
@zhuzhih2017 error log:

alicloud-ecs: Error deleting vpc, it may still be around: Aliyun API Error: RequestId: 5AA4595B-5AF2-41C2-BE1B-CA4506EA38BB Status Code: 400 Code: Forbbiden Message: Active custom route in vpc.

**Comment by willmao** [comment]
@zhuzhih2017 

i come into a very strange issue, i comment all steps in the Alicloud builder, rebuild the packer and run packer build with the following command

```
go build -o ./bin/packer .
./bin/packer build test.json
```
but packer still creates instance and vpc

Is there anything wrong?

**Comment by li-wu** [comment]
@zhuzhih2017 here is the error log:
`alicloud-ecs: Error deleting vpc, it may still be around: Aliyun API Error: RequestId: 2800BBD5-04A3-49C8-85A1-8F6D7148FB0B Status Code: 400 Code: Forbbiden Message: Active custom route in vpc.`

@willmao , thanks for providing the workaround. I will have a try.

**Comment by li-wu** [comment]
@willmao , I tried your solution: create a VPC and delete the virtual switch in it and add and option with `vpc_id: <vpc id>` but it failed with error:
`errored: The specified vpc {vpc id} doesn't exist.`  any suggestion?

**Comment by willmao** [comment]
@li-wu just make sure the vpc_id field is correctly set.

**Comment by willmao** [comment]
@li-wu i have made a PR to the packer official repo and fixed this issue.

**Comment by li-wu** [comment]
@willmao Thanks for providing the fix.

**Comment by Marcus-James-Adams** [comment]
if this is now fixed should this be closed?
