### ISSUE TITLE
which RAM access is required?

### ISSUE THREAD

**Issue by chfw** [alibaba/packer-provider#34]
Hi

I am using RAM to build ecs image. As you can see, it was forbidden. Could you please point me out which access I should have granted my robot account?

`Build 'alicloud-ecs' errored: Aliyun API Error: RequestId: 3AB7DE95-65DB-4F36-85F1-109820DDD8D0 Status Code: 403 Code: Forbidden.RAM Message: User not authorized to operate on the specified resource, or this API doesn't support RAM.`

thanks.

**Comment by willmao** [comment]
@chfw

- AliyunECSFullAccess (create ecs instance)
- AliyunVPCFullAccess (create vpc or vswitch)
- AliyunEIPFullAccess (allocate eip)

you can also setup you own ram access control policy to limit packer to access the specific region resources!

**Comment by zhuzhih2017** [comment]
@chfw Since @willmao already help answer the questions. I'll close this issue, if you still have problems, you can reopen it. thanks.
