### ISSUE TITLE
Can't create image for instance type ecs.gn5-c4g1.xlarge

### ISSUE THREAD

**Issue by jhagege** [alibaba/packer-provider#37]
Hi I'm trying to create an instance for the type ecs.gn5-c4g1.xlarge.
I get the error "InvalidDiskCategory.CreateImage".

I think it's because packer tries to create an image of the I/O-Intensive Local Disk 440GB.
I don't need to create an image of this, just of system disk.

By default, this instance type creates two disks:
![image](https://user-images.githubusercontent.com/7504908/43454075-8dc7b89a-94c4-11e8-874b-21c3fc972e65.png)

Can I instruct packer to create an image only for the system disk, and not the second disk ? 
Thanks !

**Comment by willmao** [comment]
From Alicloud web console, the ecs.gn5-c4g1.xlarge type instance creates a 440G NVMe SSD by default, just try another instance type :)

**Comment by Marcus-James-Adams** [comment]
Hi this is occurring for us too on the latest version of packer and provisioner - 
Changing to another hardware type is not an option

**Comment by chhaj5236** [comment]
@Marcus-James-Adams Thanks for reporting this issue. I'll see if we can provide an option for only creating image from the system disk.

**Comment by chhaj5236** [comment]
@jhagege @Marcus-James-Adams This feature has been satisfied by https://github.com/alibaba/packer-provider/pull/50. Supported version: [V1.2.5](https://github.com/alibaba/packer-provider/releases/tag/V1.2.5). Option `image_ignore_data_disks` can be set to `true` to ignore data disks.

**Comment by jhagege** [comment]
Thanks!

**Comment by Marcus-James-Adams** [comment]
@jhagege @chhaj5236 
after updating to new release
When setting "image_ignore_data_disks":"true",

I now immediately  get 
uild 'TEST.alicloud.eu-central-1.ecs.gn5-c4g1.xlarge' errored: Aliyun API Error: RequestId:  Status Code: 400 Code: InvalidEndpoint Message: endpoint is empty,pls check
uild 'alicloud.eu-central-1.ecs.gn5-c4g1.xlarge' errored: Aliyun API Error: RequestId:  Status Code: 400 Code: InvalidEndpoint Message: endpoint is empty,pls check

If I remove it, its launches and builds as normal but the gives the original error at the end when it tries to create the image
