### ISSUE TITLE
alicloud-ecs: Waiting for SSH to become available...

### ISSUE THREAD

**Issue by allendu91** [alibaba/packer-provider#44]
==> alicloud-ecs: Waiting for SSH to become available...
==> alicloud-ecs: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

按照https://help.aliyun.com/document_detail/60822.html 这篇官方文档执行总是卡在ssh上，请问哪里配置有问题呢？

**Comment by chhaj5236** [comment]
@allendu91 你用的是社区的Packer吗，8月份他们有个改动导致了一个keypair不生效的bug，这两天已经修复合并进去了。你可以拉取最新的代码重新编译一下再执行下

**Comment by chhaj5236** [comment]
Releated PR: https://github.com/hashicorp/packer/pull/6720. Close for now, if this problem still exist, we'll reopen the issue.
