### ISSUE TITLE
Unable to set the System Disk size

### ISSUE THREAD

**Issue by Marcus-James-Adams** [alibaba/packer-provider#47]
From my reading of the docs I need to set image_disk_mappings -> disk_size if i want a custom system disk size
"disk_size (number) - Size of the system disk, in GB, values range:"

I'm setting it in packer as follows:
"image_disk_mappings":[{"disk_size":256}],
but this always creates a secondary data disk of 256GB leaving the system disk at 40GB, custom disk sizes work ok from the console.  Is this something I am doing wrong?  How can you set a custom system disk size in packer?

**Comment by chhaj5236** [comment]
Hi @Marcus-James-Adams , thanks for submitting this issue. `image_disk_mapping` options is only applied to data disks. We may need another option to support system disk related properties. We'll support this as soon as possible.

**Comment by Marcus-James-Adams** [comment]
Thanks, its a show stopper for me as our systems need bigger system disks.
Is the following workaround possible?  I Manually create my own custom image Base OS disk that's based on a 256GB disk and then if I run packer using that as the source image will the new images have 256GB disks? or will it try and revert to a 40GB?

**Comment by chhaj5236** [comment]
@Marcus-James-Adams 
> I Manually create my own custom image Base OS disk that's based on a 256GB disk and then if I run packer using that as the source image will the new images have 256GB disks

Yes, it will do the trick.

**Comment by chhaj5236** [comment]
This feature has been satisfied by #48
