### ISSUE TITLE
WINRM Password not recognised if they contain "_" - This is a valid windows password character

### ISSUE THREAD

**Issue by Marcus-James-Adams** [alibaba/packer-provider#49]
I noticed this on the gui for ec2 launch but thought it just affected that but if you have
SNIPED For brevity
"variables": {
	"username" : "myadmin",
	"password" : "Password1With_In1t"
},
"builders" :[
	{	"name": "alicloud.eu-central-1.ecs.gn5-c4g1.xlarge",
		"communicator": "winrm",	
		"winrm_username": "{{user `username`}}",
		"winrm_password": "{{user `password`}}"}]

on packer build you get 

Build 'alicloud.eu-central-1.ecs.gn5-c4g1.xlarge' errored: Error creating instance: Aliyun API Error: RequestId: 1020D6CC-20A8-4CF9-8F7B-54EB88B239BD Status Code: 400 Code: InvalidPassword.Malformed Message: The specified parameter "Password" is not valid.
=> Some builds didn't complete successfully and had errors:

If you remove the _ from the password then they start to build.
The "_" is a valid character for windows passwords and should be allowed

**Comment by Marcus-James-Adams** [comment]
@chhaj5236 "_" is a valid windows password character - the alicloud api must support it.
For our current requirements, we can not change.

**Comment by chhaj5236** [comment]
@Marcus-James-Adams This is not a packer-provider issue. I'll close it. Your request will be estimated by alicloud team.
