### ISSUE TITLE
"image_ignore_data_disks":"true" gives error on launch

### ISSUE THREAD

**Issue by Marcus-James-Adams** [alibaba/packer-provider#51]
after updating to new release
When setting "image_ignore_data_disks":"true",

I now immediately get
uild 'TEST.alicloud.eu-central-1.ecs.gn5-c4g1.xlarge' errored: Aliyun API Error: RequestId: Status Code: 400 Code: InvalidEndpoint Message: endpoint is empty,pls check
uild 'alicloud.eu-central-1.ecs.gn5-c4g1.xlarge' errored: Aliyun API Error: RequestId: Status Code: 400 Code: InvalidEndpoint Message: endpoint is empty,pls check

If I remove it, its launches and builds as normal but the gives the original error at the end when it tries to create the image

**Comment by chhaj5236** [comment]
@Marcus-James-Adams That's wired, I'm unable to reproduce the issue you mentioned. Could you please run `packer build ...` command with `PACKER_LOG=1` prefix and paste the output.  Besides following infos are needed as well, thanks:
1. The content of your Packer configuration file
2. The Packer version you used
3. AliCloud provider version which should be V1.2.5

**Comment by chhaj5236** [comment]
@Marcus-James-Adams This error seems not related to Packer. I'll close for now. If happened again, please reopen this issue and post full logs for further investigating.
