### ISSUE TITLE
Adding a Password parameter for troubleshooting

### ISSUE THREAD

**Issue by matttrach** [alibaba/packer-provider#71]
Any chance we can get a password parameter for troubleshooting instances that fail to create? There is a disable_stop_instance flag for this purpose, I would like some way to easily login to the server. I can't find a way to get the temp key or set a password on image creation fail.

**Comment by chhaj5236** [comment]
@matttrach You can run Packer command with `-debug` option. It will store the temp key in the same directory where you run the command, and the building process will stop at each step waiting for your command to proceed.
